name: RNAUnet
channels:
  - conda-forge
  - pytorch
  - gwforg
dependencies:
  - numpy 
  - pandas
  - matplotlib 
  - scikit-learn
  - pytorch  
  - torchvision
  - torchaudio
  - cpuonly 
  - torchinfo
  - gwf

